### ISSUE TITLE
tapF bug

### ISSUE THREAD

**Issue by michaelkuk** [char0n/monadT#8]
tapF method resolves even though it contains Either.left

The following code illustrates the issue:

```javascript
const { FlutureTMonetEither: FTE } = require('monad-t')

FTE.fromValue('hello')
  .tapF(() => FTE
    .fromValue(0)
    .filter(v => v === 1, 'sad')
  )
  .promise()
  .then(console.log)
  .catch(console.log)

// Prints 'hello' instead of 'sad'
```

**Comment by michaelkuk** [comment]
Further inspection showed that the problem is in `and` operator as it takes into account only Future and not the nested either. 

Furthermore `mapRej` operator suffers from the same issue as it is capable of mapping over rejected Future but not over resolved future with Either.Left encapsulated within.

EDIT:
It seems that sources imported from src folder do work as expected, however build sources imported from lib folder experience the above mentioned issue. I shall inspect the output files and examine build process to find the issue.

**Comment by char0n** [comment]
Yes I came to the same conclusion. As you say, mapRej and and operators are affected. I've already started to work on the fixes and tests.

**Comment by michaelkuk** [comment]
There seem to be multiple issues mangled together in here. During debugging I used the following code in the monad-t project: 

```
const Future = require('fluture');
const FTE = require('./src/FlutureTMonetEither');

FTE.fromValue('hello')
  .tapF(() => FTE
    .fromFuture(Future((reject, resolve) => {
      setTimeout(() => resolve(Infinity), 200);

      return () => {};
    }))
    .filter(v => v === Infinity, () => 'sad')
  )
  .chain(() => FTE.fromValue(11))
  .promise()
  .then(console.log)
  .catch(console.error);
```

which result in following error: 
```
TypeError: g is not a function
    at /Volumes/SD_Storage/OSS/monad-t/node_modules/monet/dist/monet.js:79:22
    at init.bind (/Volumes/SD_Storage/OSS/monad-t/node_modules/monet/dist/monet.js:715:40)
    at init.map (/Volumes/SD_Storage/OSS/monad-t/node_modules/monet/dist/monet.js:108:21)
    at init.type.map (/Volumes/SD_Storage/OSS/monad-t/node_modules/monet/dist/monet.js:943:28)
    at MapAction.FlutureTMonetEither.(anonymous function).fn.constructor.of.run.(anonymous function).either [as mapper] (/Volumes/SD_Storage/OSS/monad-t/src/FlutureTMonetEither/index.js:312:24)
    at MapAction.resolved (/Volumes/SD_Storage/OSS/monad-t/node_modules/fluture/index.js:679:82)
    at resolved (/Volumes/SD_Storage/OSS/monad-t/node_modules/fluture/index.js:170:19)
    at Resolved._fork (/Volumes/SD_Storage/OSS/monad-t/node_modules/fluture/index.js:567:3)
    at drain (/Volumes/SD_Storage/OSS/monad-t/node_modules/fluture/index.js:230:25)
    at settle (/Volumes/SD_Storage/OSS/monad-t/node_modules/fluture/index.js:156:17)
```

I figured out that the problem is that somewhere FTE passes reference to itself into Monet map rather then map function. (see the pic.)

![screen shot 2017-09-04 at 13 00 03](https://user-images.githubusercontent.com/14974720/30023773-1eddd60a-9171-11e7-8816-26eeacd84e2b.png)
